apiVersion: v1
kind: Template
metadata:
  name: minio-template
  annotations:
    description: "Deploy Minio to serve existing PVC content."
    iconClass: "icon-hdd"
    tags: "minio,objectstore"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: minio-deployment
    labels:
      app: minio
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: minio
    template:
      metadata:
        labels:
          app: minio
      spec:
        containers:
        - name: minio
          image: minio/minio:latest
          command:
            - minio
            - server
            - /mnt/data
          ports:
          - containerPort: 9000
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minioSecretKey
          volumeMounts:
          - mountPath: "/mnt/data"
            name: pi-store
        volumes:
        - name: pi-store
          persistentVolumeClaim:
            claimName: pi-store
- apiVersion: v1
  kind: Secret
  metadata:
    name: minio-secret
    labels:
      app: minio
  stringData:
    minioAccessKey: ${MINIO_ACCESS_KEY}
    minioSecretKey: ${MINIO_SECRET_KEY}
- kind: Service
  apiVersion: v1
  metadata:
    name: minio-service
    labels:
      app: minio
  spec:
    selector:
      app: minio
    ports:
    - name: minio-port
      protocol: TCP
      port: 9000
      targetPort: 9000
- apiVersion: v1
  kind: Route
  metadata:
    name: minio-route
    labels:
      app: minio
  spec:
    to:
      kind: Service
      name: minio-service
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
parameters:
- name: MINIO_ACCESS_KEY
  displayName: Minio access key
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  required: true
- name: MINIO_SECRET_KEY
  displayName: Minio secret key
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true
